language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.5
      env: TOXENV=cov
install:
    - pip install --quiet tox-travis flake8
script:
    - tox
    - flake8
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet coveralls;
      coveralls;
      fi
