name: Test

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"


      - name: Install dependencies
        run: |
          python3 -m pip install Pillow

      - name: Install txtrpacker
        run: |
          python3 -m pip install .

      # TODO: create tests!
      # - name: Run tests with pytest
      #   run: pipenv run coverage run --source txtrpacker -m pytest 

      # - name: Show basic test coverage report
      #   run: pipenv run coverage report
